# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: LinuxBuild
  strategy:
    matrix:
      ubuntu-20.04:
        imageName: 'ubuntu-20.04'
      py36:
        pyVer: '3.8'
  displayName: Linux Build
  pool:
    vmImage: $(imageName)
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pyVer)'
        architecture: 'arm64'
    - script: sudo apt-get update -y
    - script: sudo apt-get install -y libxtst-dev qtdeclarative5-dev libavahi-compat-libdnssd-dev libcurl4-openssl-dev
      displayName: Install Dependencies
    - script: sh -x ./clean_build.sh
      displayName: Clean Build
